project:
  type: website
  output-dir: docs
  
website:
  title: "Maria Ambrosio, MD-MPH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/mariaambrosio/
      - icon: github
        href: https://github.com/mgambrosio/mgambrosio_website.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, created by Maria Ambrosio"

format:
  html:
    theme: cerulean
    toc: true

editor: source

